### ISSUE TITLE
ios编译错误

### ISSUE THREAD

**Issue by liusir008** [OpenInstall/openinstall-flutter-plugin#1]
error: 'OpenInstallSDK.h' file not found with <angled> include; use "quotes" instead
    #import <OpenInstallSDK.h>
            ^~~~~~~~~~~~~~~~~~
            "OpenInstallSDK.h"

**Comment by milomai** [comment]
podfile 加入 use_frameworks! 时可以重现。去掉 use_frameworks! 正常

**Comment by githublzy** [comment]
已修复，请使用1.1.2版本
