### ISSUE TITLE
使用1.3.0版本，ios应用不在后台运行时拉起失败

### ISSUE THREAD

**Issue by taoliuer** [OpenInstall/openinstall-flutter-plugin#2]
ios应用在后台运行时，可以拉起，但杀死应用后就拉起失败了（刚拉起应用就闪退）

**Comment by loadingCooper** [comment]
之前测试没有出现这种情况，请问您的问题解决了吗？请联系我们的官方技术支持：QQ 800853853

**Comment by loadingCooper** [comment]
1.3.1版本已经解决了相关问题，并且简化了集成流程。
