### ISSUE TITLE
m1芯片，运行项目到模拟器的时候报错。'openinstall_flutter_plugin/OpeninstallFlutterPlugin.h' file not found（运行真机是正确的）

### ISSUE THREAD

**Issue by guuguo** [OpenInstall/openinstall-flutter-plugin#3]
![image](https://user-images.githubusercontent.com/12984352/228255078-60bef5b2-f01b-4359-b7c4-157580d7b1d6.png)
/Users/guodeqing/guuguo/dev/flutter/read_info/ios/Runner/Runner-Bridging-Header.h:2:9: error: 'openinstall_flutter_plugin/OpeninstallFlutterPlugin.h' file not found
#import <openinstall_flutter_plugin/OpeninstallFlutterPlugin.h>
        ^
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/guodeqing/Library/Developer/Xcode/DerivedData/Runner-afxuizglrhjnpygbbekryqvwpijm/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_ZLYPNYZCEJ0Z-clang_35IMRDIIBGA6Y.pch' for bridging header '/Users/guodeqing/guuguo/dev/flutter/read_info/ios/Runner/Runner-Bridging-Header.h'
帮忙看看怎么处理下

**Comment by wenkiwu** [comment]
请联系我们的官方技术支持：QQ 800853853
