### ISSUE TITLE
init每次都会调用

### ISSUE THREAD

**Issue by spring321** [OpenInstall/openinstall-flutter-plugin#4]
final _openInstallFlutterPlugin = OpeninstallFlutterPlugin();
  void init() async {
    await getDefaultChannelCode();
    await enableAd();
    _openInstallFlutterPlugin
      ..init(dataHandler)
      ..install(dataHandler);
  }

dataHandler每次打开应用都会调用

**Comment by wenkiwu** [comment]
_openinstallFlutterPlugin.init(wakeupHandler)  
用于初始化，并且设置拉起回调  
_openinstallFlutterPlugin.install(installHandler)  
用于获取安装参数  

**SDK初始化成功后内部将会一直保存安装参数，每次调用install都会返回安装参数。**
在获取完成后如果不需要再次获取，可以在本地设置一个标识以便于下次不再调用此方法
